### ISSUE TITLE
Sequence header

### ISSUE THREAD

**Issue by giantoni** [bcgsc/RNA-Bloom#14]
Hi,

I am so sorry for this question, but I didn't find an explanation of the sequence header of RNA-Bloom output.

All my sequences have this type of header: >E4.L.4 l=306. Please, confirm if I am right:

E4 is the gene number and L4 is the isoform number?

Many thanks in advance!

Gi

- [x] RNA-Bloom v1.3.1
- [x] java version 11.0.9
- [x] exact command used to run RNA-Bloom

rnabloom -left sample_1_R1.fastq.gz -right sample_1_R2.fastq.gz -revcomp-right -ntcard -t 80 -outdir sample1_transcriptome

**Comment by kmnip** [comment]
Hi,

There is currently no gene name assigned in RNA-Bloom.
`E4.L.4` is the isoform name.
`E4` indicates that the isoform was extended from a fragment with minimum k-mer coverage >= 10,000 (1E4).
`L` indicates that the seed fragment was longer than the minimum fragment length threshold. 

Ka Ming

**Comment by Akanksha2511** [comment]
Hi, can you please explain the sequence header. for example in here ">2 l=3215 c=1529.4984 s=2" what is the before and after part . part of c. 

Thanks, 
Akanksha

**Comment by kmnip** [comment]
`l` is the sequence length
`s` is the ID of the seed sequence to used from the previous stage

**Comment by Akanksha2511** [comment]
And c ?

**Comment by kmnip** [comment]
`c` is the estimated per-base read depth. It's very experimental, not very accurate.
