### ISSUE TITLE
c=null in output FASTA

### ISSUE THREAD

**Issue by schorlton** [bcgsc/RNA-Bloom#18]
Thanks for the amazing software! Ran some cDNA long-read sequencing through assembly:
`rnabloom -long input.fastq -ntcard -t 8 -outdir assembled`

It all succeeded; however, when looking at my output data, I see that `c=null` in some of the FASTA sequence headers. I understood that the `c=`  tag was meant to include coverage, and most of theses tags look correct!

Example:
```
>3 l=228 c=null s=8
GCTGAAAGCATCTAAGTGTGAAACCCACCTCAAGATGAGATTTCCCATGATTTTATATCAGTAAGACTATCCTCAGTGGGAAATCTGTCTTGCCCTCCCTCCCGGGACCCCCCTAGGCCCGCCCCGGCATTTATCCCTTCCCCCCCGGCGGAACAACGAGTACGCCGGCGGTAAATCCACTCTGTCCTCTCGCGCAAAACGGATCGGCCTCCGCCCGCGACGGATAGA
```

# Please report
```
test$ java -version
openjdk version "11.0.9.1-internal" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 11.0.9.1-internal+0-adhoc..src, mixed mode)

test$ rnabloom -v
RNA-Bloom v1.4.3
Ka Ming Nip, Canada's Michael Smith Genome Sciences Centre, BC Cancer
Copyright 2018-present
```

**Comment by Ebedthan** [comment]
Hi,
Same issue here.

**Comment by kmnip** [comment]
This will be fixed in the next release.

**Comment by kmnip** [comment]
This bug is fixed. Please see my new release of RNA-Bloom v2.0.0: https://github.com/bcgsc/RNA-Bloom/releases/tag/v2.0.0
