### ISSUE TITLE
How to remove the isoform in the trasncript.fa file?

### ISSUE THREAD

**Issue by mathavanpu** [bcgsc/RNA-Bloom#20]
Hello ,
I am doing the denvo transcriptome assembly,  please guide me how to remove the isoforms in the  transcript.fa file, 
The output of transcript.fa file has transcript start as E1,E2, E3.
what does it mean?

# Please report

- [ ] version of RNA-Bloom with `java -jar RNA-Bloom.jar -version`
- [ ] RNA-Bloom v1.3.1

- [ ] version of java with `java -version`
- [ ] openjdk version "1.8.0_265"

- [ ] exact command used to run RNA-Bloom
- [ ] transcript.fa

**Comment by kmnip** [comment]
The assembled transcripts are assembled based on extensions of seed fragments, which were reconstructed during the 2nd stage of the assembly. These fragments were split into different coverage strata. The `E1`, `E2`, and `E3` prefixes correspond to 10^1, 10^2, and 10^3, respectively.

What are you trying to remove?

**Comment by mathavanpu** [comment]
Hello,
Thank you very much for the reply
Please tell me remove the isoforms in the trasncript.fa file

**Comment by kmnip** [comment]
I recommend using EvidentialGene:
http://arthropods.eugenes.org/EvidentialGene/about/EvidentialGene_trassembly_pipe.html

Also, refer to their preprint here:
https://www.biorxiv.org/content/10.1101/829184v1.full
