### ISSUE TITLE
FastQ gzipped files not accepted as input?

### ISSUE THREAD

**Issue by auesro** [bcgsc/RNA-Bloom#33]
# Please report

- [ ] version of RNA-Bloom with `java -jar RNA-Bloom.jar -version`
Previous command results in: Error: Unable to access jarfile RNA-Bloom.jar
So command used for RNA-Bloom version: rnabloom -v
RNA-Bloom v1.4.3
Ka Ming Nip, Canada's Michael Smith Genome Sciences Centre, BC Cancer
Copyright 2018-present

- [ ] version of java with `java -version`
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment JBR-11.0.13.7-1751.21-jcef (build 11.0.13+7-b1751.21)
OpenJDK 64-Bit Server VM JBR-11.0.13.7-1751.21-jcef (build 11.0.13+7-b1751.21, mixed mode)

- [ ] exact command used to run RNA-Bloom
rnabloom -pool readslist.txt -revcomp-right -ntcard -t 10 -mergepool -outdir /home/auesro/Desktop/RNA_Bloom/output -k 20

Error:
```
RNA-Bloom v1.4.3
args: [-pool, readslist.txt, -revcomp-right, -ntcard, -t, 10, -mergepool, -outdir, /home/auesro/Desktop/RNA_Bloom/output, -k, 20]

name:   rnabloom
outdir: /home/auesro/Desktop/RNA_Bloom/output
Pooled assembly mode is ON!
Parsing pool reads list file `readslist.txt`...
ERROR: Unsupported file format detected in input file `left`. Only FASTA and FASTQ formats are supported.
rnabloom.io.FileFormatException: Unsupported file format detected in input file `left`. Only FASTA and FASTQ formats are supported.
	at rnabloom.RNABloom.checkInputFileFormat(RNABloom.java:344)
	at rnabloom.RNABloom.main(RNABloom.java:6357)
```
My fastq files are gzipped but according to the `Readme.md`, gzip compression is supported `warning Input reads must be in either FASTQ or FASTA format and may be compressed with GZIP.`

Any ideas?

Thanks!

A

**Comment by kmnip** [comment]
Can you please report the first 10 lines of your `readslist.txt`?
You get that error when the read file you specified is not a FASTA/FASTQ file.

**Comment by auesro** [comment]
Sure, only 3 lines though:
```
#name left right
C1 /home/LAB/lab_eh_2/AER_Data/snRNAseq/C1/trimmed/A_S1_L001_R1_001_val_1.fq.gz /home/LAB/lab_eh_2/AER_Data/snRNAseq/C1/trimmed/A_S1_L001_R2_001_val_2.fq.gz
C2 /home/LAB/lab_eh_2/AER_Data/snRNAseq/C2/trimmed/C_S1_L001_R1_001_val_1.fq.gz /home/LAB/lab_eh_2/AER_Data/snRNAseq/C2/trimmed/C_S1_L001_R2_001_val_2.fq.gz
```
Yes, I know, my read files are gz compressed FASTQ files and according to your instructions, input reads can be gz compressed. But I still get that error...

**Comment by kmnip** [comment]
Ahh, you just need to remove the first line.
That will be supported in an upcoming release.

**Comment by auesro** [comment]
Ohhh
You mean I need to remove `#name left right` line from the `readlist.txt` file?

**Comment by kmnip** [comment]
Yes.
That formatting is meant for the code in the master branch. If you look at the README that came with version 1.4.3, it is not there.
Sorry for the confusion!

**Comment by auesro** [comment]
I see!
Thats great, easy to fix.

One last question: I just noticed you are also an author at the TransAbyss package...would you recommend TransAbyss or RNA-Bloom for de novo transcriptome assembly from scRNAseq data?

**Comment by kmnip** [comment]
Please use RNA-Bloom for both single-cell and bulk RNA-seq data. Thanks!

**Comment by auesro** [comment]
Will do!
Thanks for your help!
