### ISSUE TITLE
How to restart a failed run

### ISSUE THREAD

**Issue by jesgomez** [bcgsc/RNA-Bloom#35]
# Please report

- [v1.4.3 ] version of RNA-Bloom with `java -jar RNA-Bloom.jar -version`
- [ 11.0.9.1] version of java with `java -version`
- [ ] exact command used to run RNA-Bloom

Hi, 
I was running RNAbloom with long and short reads and it failed during the getting transcripts step. I'd like to know how can I restart the run from the latest checkpoint.

Thank you. 

Jèssica

**Comment by kmnip** [comment]
Hi Jessica,

You can simply re-run the exact same command and it should restart at stage 3.

Ka Ming

**Comment by weilu1998** [comment]
Hi @kmnip 

I tried to rerun a failed job (due to job time limit) from stage 3 with the exact same command, but the output log file of the new job starts from the very beginning (k-mer counting). Any suggestions?

Thanks,
Wei
