### ISSUE TITLE
Improved README: Add output files description

### ISSUE THREAD

**Issue by Ebedthan** [bcgsc/RNA-Bloom#36]
Hi @kmnip,

Thanks for the great tool. I believe the RNA-Bloom would benefit from a README section describing the output files.
I do not have full comprehension of the output files to put a PR but can help if wanted.

Thanks.
Anicet

**Comment by kmnip** [comment]
Thanks for the suggestion!
I will add a section that primarily describes the final output files for the next release.

**Comment by kmnip** [comment]
I have added some descriptions in the readme about the final output files.
Please see my new release of RNA-Bloom v2.0.0: https://github.com/bcgsc/RNA-Bloom/releases/tag/v2.0.0

Let me know if you feel more information/clarification is needed. :)
