### ISSUE TITLE
Program doesn't finish on tiny test dataset (illumina PE & ONP)

### ISSUE THREAD

**Issue by lmuenter** [bcgsc/RNA-Bloom#4]
Thanks for your active work on this program! In my opinion, hybrid-capable assemblers are the future. Sadly, I encountered a problem with RNA-Bloom.
For a tiny test dataset (Illumina PE and Nanopore cDNA-reads), the program doesn't finish or terminate on its own. It runs until being terminated by the job controller (Slurm) due to timeout. Some errors occur early on (see attached). I'm using v1.3, but these errors and behaviour also occured in v1.2.3. Any advice on this?

Installation and version:
- installed via conda
- version: 1.3 and 1.2.3

INPUT: 
A pool of 2 tissues with two replicates, a total of only 400 PE-reads. Separately, 100 long ONP-reads are given.

SETTINGS:
rnabloom --pool "$samplesFile" \
               -long "$ONP_FL" \
               --threads 4 \
               --memory 12 \
               -prefix "$prefix" \
               -ntcard \
               --outdir "$outdir"

Attachements:
[rnabloom_out.txt](https://github.com/bcgsc/RNA-Bloom/files/4667932/rnabloom_out.txt)
[rnabloom_err.txt](https://github.com/bcgsc/RNA-Bloom/files/4661704/rnabloom_err.txt)

**Comment by kmnip** [comment]
Hi @lmuenter ,

Your command is incorrect. As indicated in the readme, the `-pool` option is meant for pooled multi-sample assembly (e.g. single-cell RNA-seq data).

If you want to assemble both Illumina and Nanopore reads, you can do it like so:
```
rnabloom -left ${illumina_left.fastq} -right ${illumina_right.fastq} -rcr -long ${nanopore.fastq} -ntcard -t 4 -outdir ${outdir}
```
This hybrid assembly mode is still experimental.

Thanks,
Ka Ming

**Comment by lmuenter** [comment]
Thank you very much, the program is now failing successfully. However, I thought the "pool" could be used analogous to the dataset files of rnaSPAdes and Trinity (they come in handy)? I was pooling paired-end reads from several experiments with 3 replicates each. Seems like I was wrong!
Thanks again,

Lukas

**Comment by kmnip** [comment]
You can assemble multiple replicates together, e.g.

```
rnabloom -left ${rep1_left.fq} ${rep2_left.fq} -right ${rep1_right.fq} ${rep2_right.fq} -rcr -long ${rep1_long.fq} ${rep2_long.fq} -ntcard -t 4 -outdir ${outdir}
```
