### ISSUE TITLE
Release memory before redundancy reducing step.

### ISSUE THREAD

**Issue by xiekunwhy** [bcgsc/RNA-Bloom#40]
Hi,

Is it possible to run redundancy reducing step only or release memory usage before redundancy reducing step? Rna-bloom + Minimap2 may double the momery consuming.

Best,
Kun

**Comment by kmnip** [comment]
Thanks for the suggestion. I will on improving this!

**Comment by kmnip** [comment]
Technically, RNA-Bloom isn't using much memory at the redundancy reduction step. The primary issue is that there are too many input sequences for minimap2.

I am testing an idea and I may incorporate it in the next release.

**Comment by xiekunwhy** [comment]
Hi @kmnip ,

Any progress?

Best regards,
Kun

**Comment by kmnip** [comment]
Hi Kun,
I will make a new release later this month. I will let you know. Thanks for your patience!
Ka Ming

**Comment by kmnip** [comment]
@xiekunwhy Sorry for the delays... This issue is fixed now. Please see my new release of RNA-Bloom v2.0.0: https://github.com/bcgsc/RNA-Bloom/releases/tag/v2.0.0
