### ISSUE TITLE
We really need to keep E0.L. sequence?

### ISSUE THREAD

**Issue by xiekunwhy** [bcgsc/RNA-Bloom#41]
Hi,

I found many E0.L. sequences (2 to 3 or more times than other E sequences) in rna-bloom's assembly (in all samples I have tested), but the busco results with or withou E0.L. sequences are almost the same. Is it necessary to keep E0.L. sequences?

Or is there an option to tell rna-bloom not to output E0.L. sequences?

Best,
Kun

**Comment by xiekunwhy** [comment]
-stratum e1 help me a lot, with this option, the transcript number of all sample I have tested (40+ pooled RNA-seq samples from difference species) were near the expected number.

**Comment by kmnip** [comment]
Thanks Kun for your report. I am that it worked for you! :)
