### ISSUE TITLE
Illumina PE (Stranded) and PacBio Reads for RNA-Seq

### ISSUE THREAD

**Issue by sum732** [bcgsc/RNA-Bloom#5]
Hello,
While looking for a hybrid assembler came across RNABloom. I test rnaSpades and was not happy with the assembly. I read about RNABloom and its mentioned that ONT reads can be used. I am wondering if RNABloom is tested with PacBio reads and can I use it as hybrid assembler (illumnina +PacBio for transcriptome assembly). 
Thanks,
Deep

**Comment by kmnip** [comment]
Hi @sum732 ,

Thanks for your interest in using RNA-Bloom!
Hybrid assembly is currently an experimental feature in RNA-Bloom.

To run in hybrid mode, you just have to list your Illumina PE reads for `-left` and `-right` and your long reads for `-long`. Here is an example for non-stranded long reads:

```
java -jar RNA-Bloom.jar -left ${illumina_left.fastq} -right ${illumina_right.fastq} -long ${long.fastq} -ntcard -t ${threads} -outdir ${outdir}
```

Are your PacBio Reads stranded? If so, are they in the same orientation as the transcript? or reverse-complemented?

**Comment by sum732** [comment]
Thanks for promptly responding.
I was just not sure is ```-long``` with with PacBio reads ( there are examples that show ONT, so i thought that its optimized for ONT and not PacBio). 
The PacBio reads are unstranded.

**Comment by kmnip** [comment]
You can try it for PacBio. It's just the settings for mapping are not optimized for PacBio reads. I will add an option for that in the next release.

Since the PacBio reads are unstranded, you can run in non-stranded mode, as shown previously.

**Comment by sum732** [comment]
Great, thanks, I will try that. 
I am facing an issue with the racon, perhaps you can help. Will create a new thread
