### ISSUE TITLE
ERROR: Error during redundancy reduction!

### ISSUE THREAD

**Issue by xiekunwhy** [bcgsc/RNA-Bloom#50]
# Please report

- [x] version of RNA-Bloom with `java -jar RNA-Bloom.jar -version`
/Bio/User/software/anaconda3/envs/rnabloom/bin/rnabloom
RNA-Bloom v2.0.0

- [x] version of java with `java -version`

/Bio/User/software/anaconda3/envs/rnabloom/bin/java -version
openjdk version "17.0.3-internal" 2022-04-19
OpenJDK Runtime Environment (build 17.0.3-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 17.0.3-internal+0-adhoc..src, mixed mode, sharing)

- [x] exact command used to run RNA-Bloom

source /Bio/User/software/anaconda3/bin/activate /Bio/User/software/anaconda3/envs/rnabloom;/Bio/User/software/anaconda3/envs/rnabloom/bin/rnabloom -revcomp-right -t 10 -ntcard -prefix R21051817_000 -left /state/partition1/WORK/Bio/Project/xiek/project/GDDXXXX_std_4/pipe/pipe3/02.mrna/04.assemble/denovoasm/R21051817_1.fq.gz -right /state/partition1/WORK/Bio/Project/xiek/project/GDDXXXX_std_4/pipe/pipe3/02.mrna/04.assemble/denovoasm/R21051817_2.fq.gz -outdir /state/partition1/WORK/Bio/Project/xiek/project/GDDXXXX_std_4/pipe/pipe3/02.mrna/04.assemble/denovoasm/R21051817_rnabloom -q 3 -Q 20 -c 1 -e 1 -bound 1000 -extend -stratum e0

Reducing redundancy in assembled transcripts...
Parsed 0 overlap records in 0.011s
before: 88,142	after: 88,142
ERROR: Error during redundancy reduction!

Best,
Kun

**Comment by kmnip** [comment]
Thanks Kun for reporting this!
In this case, you can use `transcripts.fa` (instead of `transcripts.nr.fa`) as your assembly.
