### ISSUE TITLE
RNA-Bloom2 version 

### ISSUE THREAD

**Issue by ARW-UBT** [bcgsc/RNA-Bloom#52]
Hi, 
I found your RNA-Bloom2 manuscript at bioRxive, and I would like to make sure that I correctly understand the versioning: 
Is RNA-Bloom2 of the manuscript identical to RNA-Bloom v2.0.1 here at github or at bioconda?

Best regards

**Comment by kmnip** [comment]
We used RNA-Bloom v2.0.0 for our preprint on bioRxiv.
v2.0.1 is an updated version with several bug-fixes as described in the release description.
