### ISSUE TITLE
conda install url not working

### ISSUE THREAD

**Issue by dvirdi01** [bcgsc/RNA-Bloom#58]
# Please report
Hello I was trying to install rna bloom with the mamba install command but it gives me an error message saying invalid URL and so it is not installing it. I am not sure what is wrong?
I used the following command: mamba install -c bioconda rnabloom

It says URL rejected: Malformed input to URL function
Donwload error (3) URL using bad/illegal format or missing URL

**Comment by kmnip** [comment]
The `mamba install` command worked perfectly fine on my end in a new environment.

I am suspecting that your channels are not set up properly. FYI, see https://bioconda.github.io
Run these commands and try again:
```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda config --set channel_priority strict
```
