### ISSUE TITLE
Racon Installation

### ISSUE THREAD

**Issue by sum732** [bcgsc/RNA-Bloom#6]
Hi Ka Ming,

I am trying to install the dependecies for RNABloom, namely Racon and keep seeing following error
```
CMake Error at CMakeLists.txt:51 (add_subdirectory):
  The source directory

    /Research/Programs/Racon/racon-master/vendor/bioparser

  does not contain a CMakeLists.txt file.
```
I followed the instructions:
```
git clone --recursive https://github.com/lbcb-sci/racon.git racon
cd racon
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
```
I have following compilers version in my path
```
CMake/3.2.3-goolf-1.4.10
GCC/4.7.2
```
I am on a cluster and trying to install locally. 

You may have some suggestions to try. 

Thanks
Deep

**Comment by kmnip** [comment]
Make sure that you are in the `build` directory. The error was basically saying that `CMakeLists.txt` wasn't found in the parent directory.

**Comment by sum732** [comment]
actually I was using zip file and that does get all the subrepos that are required. 
so used ```git clone``` with ``` recursive``` and it with some more GCC and G++ issues that I was able to resolved using 
```cmake -DCMAKE_C_COMPILER=/somepath/gcc ``` ```-DCMAKE_CXX_COMPILER=/somepath/g++ -DCMAKE_BUILD_TYPE=Release .. ``` and ```make``` from here "https://github.com/lbcb-sci/racon/issues/23" and it worked.
