### ISSUE TITLE
Java out of memory exception

### ISSUE THREAD

**Issue by dvirdi01** [bcgsc/RNA-Bloom#60]
I ran bloom on multiple fastq files together by giving it 200GB ram. It gave me out of memory exception mid way. I was running the command using a salloc allocation on the server and for that I need to specify the amount of space I am allocating for it on the server. I gave it 200GB to begin with but I guess it wasn't enough. I there a way to see how much space it would need for all the jobs beforehand?

Also, I want to produce a transcriptome.fq file for each of my 17 input files. I put the path to all input files inside a txt file and gave that txt file as the input. Will it go through each file and create a transcriptome.fq file for each one separately (desired output) or would it create only one transcriptome.fq file at the end?

**Comment by dvirdi01** [comment]
If I run it through snakemake by giving it all 17 input files would it again output just a single transcriptome.fq at the end? Or one for each input file?

**Comment by kmnip** [comment]
If you provide multiple FASTQ files to RNA-Bloom in one command, RNA-Bloom will create one assembly.
If you have 17 separate RNA-Bloom commands, then there will be 17 assemblies.

Also, the final output assembly of RNA-Bloom is a FASTA files, not a FASTQ file.
