### ISSUE TITLE
RNABloom not creating transcriptome files 

### ISSUE THREAD

**Issue by dvirdi01** [bcgsc/RNA-Bloom#62]
I ran rnabloom on several of my input files individually. out of my 10 samples, it did not produce any transcriptome file for 2 of them. Why is that? It finished running but there are no output files.
I ran the following command: rnabloom -long sample.fastq -t 48 -outdir .../.../sample -k 10 -e 5

These are my versions: 
- RNA-Bloom v2.0.1
- openjdk 20.0.2-internal 2023-07-18

**Comment by kmnip** [comment]
Please remove the options `-k 10 -e 5` and try again.
If the issue persists, please report the entire log file.

**Comment by dvirdi01** [comment]
Hi, I have run my files with both -k 10 e 5 and with the default settings in the past. It produces the transcriptome file for the default setting command but not for -k 10 e 5. This is the message I get for the -k 10 -e5 one: 

Parsing `sample.fastq`...
Parsed 21,301,762 sequences in 2h 7m 13s
DBG Bloom filter FPR:                 1.04 %
Counting Bloom filter FPR:            1.04 %
> Stage 1 completed in 2h 7m 13s

> Stage 2: Correct long reads for "rnabloom"
Parsing `sample.fastq`...
Corrected Read Lengths Sampling Distribution (n=10000)
        min     q1      med     q3      max
        10      193     364     715     2643
Parsed 21,301,762 sequences.
        Kept:      21,301,202   (100.0 %)
        Discarded: 560  (0.00263 %)
        Artifacts: 4,220,516    (19.81299%)
Corrected reads in 1h 43m 33s
Extracting seed sequences...
strobemers: n=3, k=11, wMin=12, wMax=61, depth=3
Bloom filter FPR:       91.0 %
before: 20,782,469      after: 15,730 (0.0757 %)
too short: 0
Extraction completed in 43m 1s
> Stage 2 completed in 2h 26m 35s

> Stage 3: Assemble long reads for "rnabloom"
Overlapping sequences...
Parsed 231,695 overlap records in 15.355s
total reads:    15,730
 - unique:      5,086   (32.3 %)
   - multi-seg: 1,193
Unique reads extracted in 0.638s
Overlapping sequences...
Parsed 44,253 overlap records in 2.313s
contained reads: 1,697
dovetail reads:  1,746
G: |V|=3,493 |E|=4,118
G: |V|=3,337 |E|=3,470
before: 6,368   after: 4,136
Laid out paths in 0.232s
Mapping sequences...
Mapping completed in 1h 4m 25s
Polishing sequences...
Error running command! See log file at `/.../.../../../sample/rnabloom.longreads.assembly4.pol.fa.log`
Polishing completed in 4m 16s
ERROR: Error polishing reads to unitigs!
ERROR: Error assembling long reads!

**Comment by kmnip** [comment]
For the first run, the Racon command was killed for some unknown reason. I don't think it has to with memory or the  `-k` or `-e` options.

The second run with multiple input files ran out of Java heap space. As mentioned [previously](https://github.com/bcgsc/RNA-Bloom/issues/61), you can increase the max Java heap space if you have enough RAM.
