### ISSUE TITLE
RAM requirements. What is the minimum?

### ISSUE THREAD

**Issue by nriareal** [bcgsc/RNA-Bloom#69]
Hello,

I just wanted to ask what the minimum RAM requirements are for using RNA-Bloom.

I am interested in performing a _de novo_ alignment of a pathogen transcriptome from previously unaligned reads of the host alignment to the host reference genome (I used HISAT2). In my case I have short reads and I was thinking to assemble them following the "multi-sample RNA-seq data with pooled assembly mode ". I have 36 samples (4 conditions, 8 biological replicates). For one condition each replicate has approximately 14,000,000 reads, while for the rest it is 4,000,000 reads. Is this feasible with 32GB of RAM (4 cores)? If not, what would you recommend? 

Thank you,
Nuria

**Comment by kmnip** [comment]
Hi @nriareal 

It's hard to say based on the number of reads alone.
The key contributor to RNA-Bloom's peak memory usage for short-read assembly is the number of unique k-mers in the reads.
I suggest you try to run the assembly. After K-mer counting, RNA-Bloom will fail when there isn't enough RAM to construct the Bloom filters.

Ka Ming

**Comment by nriareal** [comment]
Yes, it did fail after the K-mer counting. Now I have used another computer with 100 Gb RAM and it did work (although I have an unexpected output that I will comment in another issue). Thanks!
