### ISSUE TITLE
Correct  Strand Information and Pairing

### ISSUE THREAD

**Issue by sum732** [bcgsc/RNA-Bloom#7]
Hi Ka Ming,

The strandedness confuses me ( and hopefully others), so just to get this part right. I have Illumina PE which is stranded and PacBio Long reads, which are not stranded. 

Now typically before alignments and processing I consult the following to ensure I am giving the right orientation " https://github.com/igordot/genomics/blob/master/notes/rna-seq-strand.md"
The ```reverse``` option is true for a typical dUTP ( Illumina TruSeq or NEB etc).

In the detailed README you have mentioned that: 
``` -left /path/to/reads_2.fastq -right /path/to/reads_1.fastq```

So the order you have mentioned above for left (R2) and right (r1)  refers to the ```reverse ``` as above mentioned? 
Thanks!!

**Comment by kmnip** [comment]
Yes, you are correct.
The `_2` reads are the "left" reads and they are in the forward orientation, whereas the `_1` reads are the "right" reads and they are in the reverse orientation.
