### ISSUE TITLE
is the assembly deterministic?

### ISSUE THREAD

**Issue by alexyfyf** [bcgsc/RNA-Bloom#75]
# Please report

- [ RNA-Bloom v2.0.1] version of RNA-Bloom with `java -jar RNA-Bloom.jar -version`
- [ openjdk 11.0.13 2021-10-19] version of java with `java -version`
- [ rnabloom -long ${raw_reads} -stranded -t 48 -outdir ${base}] exact command used to run RNA-Bloom

Hi,
I noticed the RNAbloom2 output for long read is non-deterministic and if I rerun with the same data, the result is slightly different (at least the number is not same). I'm wondering if this is designed or expected?

Thank you

**Comment by kmnip** [comment]
The assembly is not 100% deterministic, especially when multi-threading is used.

**Comment by alexyfyf** [comment]
> The assembly is not 100% deterministic, especially when multi-threading is used. 

Thank you for confirming this. So would it be deterministic in single thread? Just out of curiosity.

**Comment by kmnip** [comment]
> > The assembly is not 100% deterministic, especially when multi-threading is used.
> 
> Thank you for confirming this. So would it be deterministic in single thread? Just out of curiosity.

It should be deterministic in single thread.
