### ISSUE TITLE
Containerized rnabloom returning "Unsupported file format detected" error for fastq.gz files when used with Nextflow

### ISSUE THREAD

**Issue by tonyaseverson** [bcgsc/RNA-Bloom#79]
# Please report

- [x] version of RNA-Bloom with `java -jar RNA-Bloom.jar -version`
rnabloom_2.0.1--hdfd78af_1.sif 

- [x] version of java with `java -version`
Picked up JAVA_TOOL_OPTIONS: -Xmx2g
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)

- [x] exact command used to run RNA-Bloom
`rnabloom -stranded -ntcard -fpr 0.005 -k 25-150:5 -extend -t 8 -outdir "rnabloom/br" -rcr -pool "rnabloom_br.txt"`

Here is the complete list of modules loaded on the DRAC cluster:
```
Currently Loaded Modules:
  1) CCconfig            5) hwloc/2.9.1        9) ucc/1.2.0               13) StdEnv/2023                  (S)  17) postgresql/16.0  (t)
  2) gentoo/2023   (S)   6) ucx/1.14.1        10) openmpi/4.1.5   (m)     14) mii/1.1.2                         18) apptainer/1.2.4
  3) gcccore/.12.3 (H)   7) libfabric/1.18.0  11) flexiblas/3.3.1         15) python/3.11 -> python/3.11.5 (t)  19) nextflow/23.10.0
  4) gcc/12.3      (t)   8) pmix/4.2.4        12) imkl/2023.2.0   (math)  16) java/17.0.6                  (t)
```

I am trying to get RNABloom to run with Nextflow, but when I run Nextflow with a manifest containing 9 paired reads I get the following messages:

```
Command exit status:
  1

Command output:
  RNA-Bloom v2.0.1
  args: [-stranded, -ntcard, -fpr, 0.005, -k, 25-150:5, -extend, -t, 8, -outdir, rnabloom/br, -rcr, -pool, rnabloom_br.txt]

  name:   rnabloom
  outdir: rnabloom/br
  Pooled assembly mode is ON!
  Parsing pool reads list file `rnabloom_br.txt`...
  ERROR: Unsupported file format detected in input file `/home/tfsevers/scratch/data/transcriptomes/resynthesized_bnapus/bbsplit_cleaned/10734406/br0\
401_2.cleaned.cleaned.fq.gz`. Only FASTA and FASTQ formats are supported.

Command error:
  rnabloom.io.FileFormatException: Unsupported file format detected in input file `/home/tfsevers/scratch/data/transcriptomes/resynthesized_bnapus/bb\
split_cleaned/10734406/br0401_2.cleaned.cleaned.fq.gz`. Only FASTA and FASTQ formats are supported.
        at rnabloom.RNABloom.checkInputFileFormat(RNABloom.java:348)
        at rnabloom.RNABloom.checkInputFileFormat(RNABloom.java:354)
        at rnabloom.RNABloom.main(RNABloom.java:6566)
```

Here is the first line of the sample manifest (with tilde inserted in place of the fully specified home dir):

```
br ~/scratch/data/transcriptomes/resynthesized_bnapus/bbsplit_cleaned/10734406/br0401_2.cleaned.cleaned.fq.gz ~/scratch/data/transcriptomes/resynthesized_bnapus/bbsplit_cleaned/10734406/br0401_1.cleaned.cleaned.fq.gz
```

When I run the container independent of Nextflow, it works fine with the same sample manifest and files. Do you have any insight into why the container would fail to recognize gzipped fastq files when it is run by a workflow manager? (I've also posted a question to the Nextflow slack.)

**Comment by tonyaseverson** [comment]
Just following up to let you know that I figured out what the problem was. I hadn't given Nextflow the instructions it needed to stage the files properly. Nextflow seems to be running RNABloom now.

**Comment by kmnip** [comment]
> Just following up to let you know that I figured out what the problem was. I hadn't given Nextflow the instructions it needed to stage the files properly. Nextflow seems to be running RNABloom now.

@tonyaseverson  Glad to hear that you had figured it out!
